CREATE USER IF NOT EXISTS 'adriano'@'%' IDENTIFIED BY 'adriano';

CREATE DATABASE IF NOT EXISTS impacta;

ALTER DATABASE impacta
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON impacta.* TO 'adriano'@'%' IDENTIFIED BY 'adriano';
